Wczytaj plik data.csv do obiektu DataFrame. Następnie wykorzystując klasę StandardScaler z pakietu scikit-learn dokonaj standaryzacji wszystkich kolumn. Tak otrzymany obiekt DataFrame wyświetl do konsoli.

In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler


np.set_printoptions(precision=4, suppress=True)

In [2]:
df = pd.read_csv('data.csv')

In [3]:
df

var1   var2    var3    var4     var5
0    12.47  18.60   81.09   481.9  0.09965
1    18.94  21.31  123.60  1130.0  0.09009
2    15.46  19.48  101.70   748.9  0.10920
3    12.40  17.68   81.47   467.8  0.10540
4    11.54  14.44   74.65   402.9  0.09984
..     ...    ...     ...     ...      ...
138  14.64  15.24   95.77   651.9  0.11320
139  14.45  20.22   94.49   642.7  0.09872
140  11.04  16.83   70.92   373.2  0.10770
141  19.81  22.15  130.00  1260.0  0.09831
142  10.26  12.22   65.75   321.6  0.09996

[143 rows x 5 columns]

In [4]:
#standaryzacja kolumn
scaler = StandardScaler()
scaler.fit(df)

StandardScaler()

In [5]:
df

var1   var2    var3    var4     var5
0    12.47  18.60   81.09   481.9  0.09965
1    18.94  21.31  123.60  1130.0  0.09009
2    15.46  19.48  101.70   748.9  0.10920
3    12.40  17.68   81.47   467.8  0.10540
4    11.54  14.44   74.65   402.9  0.09984
..     ...    ...     ...     ...      ...
138  14.64  15.24   95.77   651.9  0.11320
139  14.45  20.22   94.49   642.7  0.09872
140  11.04  16.83   70.92   373.2  0.10770
141  19.81  22.15  130.00  1260.0  0.09831
142  10.26  12.22   65.75   321.6  0.09996

[143 rows x 5 columns]

In [6]:
scaled = scaler.transform(df)
print(scaled)

[[-0.4785 -0.2137 -0.4584 -0.5114  0.0636]
 [ 1.3742  0.3895  1.2924  1.4055 -0.616 ]
 [ 0.3777 -0.0178  0.3905  0.2783  0.7424]
 [-0.4986 -0.4185 -0.4427 -0.5531  0.4723]
 [-0.7449 -1.1397 -0.7236 -0.745   0.0771]
 [ 1.8496  2.1747  1.9719  1.8048  1.3537]
 [ 2.2534  0.5208  2.2644  2.4466  0.5363]
 [ 0.9819 -1.0039  0.9382  0.8882 -0.0203]
 [-0.2294 -0.8236 -0.236  -0.3987  0.6429]
 [-0.069  -0.6544 -0.1338 -0.1639 -2.1663]
 [-0.2666  1.2665 -0.3344 -0.3457 -0.7709]
 [ 0.7557 -0.1692  0.7035  0.6847 -0.7183]
 [ 0.2374  0.0445  0.1351  0.1047 -1.0339]
 [ 0.6068  0.5164  0.6293  0.5087  1.2613]
 [-0.5158 -1.6227 -0.5469 -0.551  -0.6202]
 [ 1.4201  1.498   1.5189  1.4114  1.6167]
 [ 0.1916 -1.0818  0.1005  0.0766 -0.9977]
 [-1.14    0.0066 -1.1321 -1.0148  0.1098]
 [-2.0504 -1.3645 -1.9945 -1.5123  1.2968]
 [ 1.8353  0.2893  1.8772  1.932   0.4154]
 [-0.0977 -0.8392 -0.0737 -0.2091  0.1382]
 [-0.5845 -0.4096 -0.5827 -0.617   0.2946]
 [ 2.1388  0.6054  2.149   2.2248  1.2755]
 [-1.1773  